export const productsArray = [
   {
      productName: "Wooden Chair",
      category: "Furniture",
      material: "Wood",
      weight: "10 kg",
      color: "Brown",
      price: 150.0,
   },
   {
      productName: "Plastic Water Bottle",
      category: "Kitchenware",
      material: "Plastic",
      weight: "0.2 kg",
      color: "Blue",
      price: 5.99,
   },
   {
      productName: "Cotton T-Shirt",
      category: "Apparel",
      material: "Cotton",
      weight: "0.3 kg",
      color: "White",
      price: 12.5,
   },
   {
      productName: "Metallic Desk Lamp",
      category: "Lighting",
      material: "Metal",
      weight: "2 kg",
      color: "Silver",
      price: 35.75,
   },
   {
      productName: "Glass Vase",
      category: "Decor",
      material: "Glass",
      weight: "0.5 kg",
      color: "Transparent",
      price: 20.0,
   },
   {
      productName: "Leather Wallet",
      category: "Accessories",
      material: "Leather",
      weight: "0.1 kg",
      color: "Black",
      price: 29.99,
   },
   {
      productName: "Ceramic Dinner Plate",
      category: "Kitchenware",
      material: "Ceramic",
      weight: "0.6 kg",
      color: "White",
      price: 8.75,
   },
   {
      productName: "Aluminum Laptop Case",
      category: "Electronics",
      material: "Aluminum",
      weight: "1.5 kg",
      color: "Silver",
      price: 45.5,
   },
];
